### ISSUE TITLE
Homework1

### ISSUE THREAD

**Issue by djmaster458** [djmaster458/steamed-ham#1]
## Overview
Homework 1 has been posted. This includes making an SRS (System Requirements Standards) document. This is a rather large document consisting of many different sections.

We will also need to make a class model diagram and one other diagram to show the system design.

All of this must be completed by Sep 18th.

## To-Do
- [x] Assign sections of SRS to each team member
- [x] Complete Rough Draft by Sep 9th
- [x] Review each others sections
- [x] Cleanup and Turn In

## Resources
See Blackboard
Link to Document: https://cardmaillouisville-my.sharepoint.com/:w:/g/personal/djosbo04_louisville_edu/EewKU6ieXmBHlvcmP5vhEBQB98KH6lXr_53YPeCfKVMhIg?e=PeW6w0

**Comment by djmaster458** [comment]
Hey @bradams @Vanlichtinstein1945 @Buffal0-Bill @LukiePookie1 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/cse-550-project-630e519219127900112a1027/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
